name: Deploy to production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'
      - name: install dependencies
        run: npm install --legacy-peer-deps
      - name: npm run lint
        run: npm run lint
      - name: build project
        run: npm run build
      - name: test project
        run: npm run test
      - name: Configure AWS Credentials for China region audience
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: ${{vars.AWS_REGION}}
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          role-session-name: ${{vars.AWS_ROLE_SESSION_NAME}}
      - name: log role
        run: aws sts get-caller-identity
