name: lint and build
on:
  workflow_dispatch:
  pull_request:
jobs:
  lint-and-build:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    env:
      HARDCODED_ENV: MY custom env variablee
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: environment is
        run: echo ${{github.ref_name}}
      - name: print hardcoded environment
        run: echo ${{ env.HARDCODED_ENV }}
      - name: print my environment
        run: echo ${{ vars.MY_ENV_NAME }}
      - name: print my secret
        run: echo ${{ secrets.MY_SECRET_NAME }}