name: Test aws-ecr-credentials
on:
  push:
    branches:
      - prod
      - dev
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  test-aws:
    environment: ${{github.ref_name}}
    runs-on: ubuntu-latest
    steps:
      - name: log repo info
        run: echo ${{github.repository}}
      - name: log repository name
        run: |
          echo REPO_NAME="${GITHUB_REPOSITORY#*/}"
          echo repo name is $REPO_NAME
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
      - name: log repository owner
        run: echo ${{github.repository_owner}}
      - name: log repository owner with bash
        run: |
          echo $GITHUB_REPOSITORY_OWNER