name: Test aws-ecr-credentials
on:
  push:
    branches:
      - prod
      - dev
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  test-aws:
    environment: ${{github.ref_name}}
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: '23'
      - name: install dependencies
        run: npm install --legacy-peer-deps
      - name: build project
        run: npm run build
      - name: run tests
        run: npm run test
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: ${{ vars.AWS_SESSION_NAME }}
      - name: login to ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: prepare environments
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          COMMIT_HASH=$(git rev-parse --short $GITHUB_SHA)
          DOCKER_LATEST_VERSION_ID=${ECR_REPOSITORY}:${COMMIT_HASH}
          DOCKER_LATEST_VERSION_TAG=${ECR_REPOSITORY}:latest
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          echo "DOCKER_LATEST_VERSION_ID=$DOCKER_LATEST_VERSION_ID" >> $GITHUB_ENV
          echo "DOCKER_LATEST_VERSION_TAG=$DOCKER_LATEST_VERSION_TAG" >> $GITHUB_ENV
      - name: log prepared environments
        run: |
          echo "REPO_NAME is $REPO_NAME"
          echo "COMMIT_HASH is $COMMIT_HASH"
          echo "DOCKER_LATEST_VERSION_ID is $DOCKER_LATEST_VERSION_ID"
          echo "DOCKER_LATEST_VERSION_TAG is $DOCKER_LATEST_VERSION_TAG"
      - name: build docker image
        run: |
          docker build -t $DOCKER_LATEST_VERSION_ID  -t $DOCKER_LATEST_VERSION_TAG .
      - name: list docker image
        env:
         ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          docker images | grep $ECR_REPOSITORY
      - name: push docker image to ecr
        run: |
         docker push $ECR_REPOSITORY --all-tags


        