name: lint and build
on:
  workflow_dispatch:
  pull_request:
jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    env:
      MY_ENV: MY custom env variablee
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: print env
        run: echo $MY_ENV
      - name: print env
        run: echo {{env.MY_ENV}}
      - name: run build
        run: npm run build